language: smalltalk

sudo: false

dist: trusty

smalltalk_edge:
  source: feenkcom/smalltalkCI
  branch: master

os:
  - linux
  
branches:
  only:
    - master

smalltalk:
  - Pharo64-7.0

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
    fi

after_success:
  - |
    ls "$SMALLTALK_CI_IMAGE"
    # export PROJECT_NAME="GToolkit-Inspector"
    # customize the name of the build folder
    # export ARTIFACT_DIR="${PROJECT_NAME}"
    # mkdir "$ARTIFACT_DIR"
    # cp "$SMALLTALK_CI_IMAGE" "${ARTIFACT_DIR}/${PROJECT_NAME}.image"
    # cp "$SMALLTALK_CI_CHANGES" "${ARTIFACT_DIR}/${PROJECT_NAME}.changes"
    # export build_zip="${ARTIFACT_DIR}.zip"
    # zip -qr "$build_zip" "$ARTIFACT_DIR"
    curl -LO https://raw.github.com/stephanmg/travis-dependent-builds/master/trigger.sh
    chmod +x trigger.sh
    ./trigger.sh feenkcom gtoolkit master $TRAVIS_ACCESS_TOKEN
